"""initial schema

Revision ID: ed0839c50901
Revises: 
Create Date: 2026-08-15 00:59:04.109045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed0839c50901'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('plans',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'invited', 'disabled')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'suspended', 'deleted')", name='ck_organizations_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_organizations_status_live', 'organizations', ['status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('ai_runs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('run_type', sa.String(length=60), nullable=False),
    sa.Column('related_entity_type', sa.String(length=30), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ck_ai_runs_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_runs_org_created', 'ai_runs', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_ai_runs_org_status', 'ai_runs', ['organization_id', 'status'], unique=False)
    op.create_index('ix_ai_runs_related_entity', 'ai_runs', ['related_entity_type', 'related_entity_id'], unique=False)
    op.create_table('marketplace_connections',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('marketplace_id', sa.SmallInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('external_account_id', sa.String(length=200), nullable=True),
    sa.Column('credentials_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='disconnected', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('connected', 'disconnected', 'error', 'expired')", name='ck_marketplace_connections_status'),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'marketplace_id', 'external_account_id', name='uq_marketplace_connections_org_marketplace_account')
    )
    op.create_index('ix_marketplace_connections_org_status', 'marketplace_connections', ['organization_id', 'status'], unique=False)
    op.create_table('organization_members',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='invited', nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('invited', 'active', 'removed')", name='ck_organization_members_status'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_members_org_user')
    )
    op.create_index('ix_organization_members_org_status', 'organization_members', ['organization_id', 'status'], unique=False)
    op.create_index('ix_organization_members_user_id', 'organization_members', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), server_default='USD', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name='ck_products_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sku', name='uq_products_org_sku')
    )
    op.create_index('ix_products_org_status_live', 'products', ['organization_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='trialing', nullable=False),
    sa.Column('billing_provider', sa.String(length=30), server_default='stripe', nullable=False),
    sa.Column('external_subscription_id', sa.String(length=200), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('trialing', 'active', 'past_due', 'canceled', 'expired')", name='ck_subscriptions_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_organization_id', 'subscriptions', ['organization_id'], unique=False)
    op.create_index('uq_subscriptions_live_per_org', 'subscriptions', ['organization_id'], unique=True, postgresql_where=sa.text("status IN ('trialing', 'active')"))
    op.create_table('usage_tracking',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('metric_key', sa.String(length=60), nullable=False),
    sa.Column('period_type', sa.String(length=10), server_default='month', nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period_type IN ('day', 'month', 'billing_cycle')", name='ck_usage_tracking_period_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'metric_key', 'period_type', 'period_start', name='uq_usage_tracking_org_metric_period')
    )
    op.create_index('ix_usage_tracking_org_period_start', 'usage_tracking', ['organization_id', 'period_start'], unique=False)
    op.create_table('listings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('marketplace_connection_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), server_default='USD', nullable=False),
    sa.Column('listing_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('external_listing_id', sa.String(length=200), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketplace_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'publishing', 'active', 'error', 'ended')", name='ck_listings_status'),
    sa.ForeignKeyConstraint(['marketplace_connection_id'], ['marketplace_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listings_connection_status', 'listings', ['marketplace_connection_id', 'status'], unique=False)
    op.create_index('ix_listings_org_status', 'listings', ['organization_id', 'status'], unique=False)
    op.create_index('ix_listings_product_id', 'listings', ['product_id'], unique=False)
    op.create_index('uq_listings_external_id_per_connection', 'listings', ['marketplace_connection_id', 'external_listing_id'], unique=True, postgresql_where=sa.text('external_listing_id IS NOT NULL'))
    op.create_index('uq_listings_live_product_per_connection', 'listings', ['marketplace_connection_id', 'product_id'], unique=True, postgresql_where=sa.text("status <> 'ended'"))
    op.create_table('product_assets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='upload', nullable=False),
    sa.Column('derived_from_asset_id', sa.UUID(), nullable=True),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('asset_type', sa.String(length=20), server_default='image', nullable=False),
    sa.Column('marketplace_id', sa.SmallInteger(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ready', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('image', 'video', 'document')", name='ck_product_assets_asset_type'),
    sa.CheckConstraint("source IN ('upload', 'ai_generated', 'processed')", name='ck_product_assets_source'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'ready', 'failed')", name='ck_product_assets_status'),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['derived_from_asset_id'], ['product_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_product_assets_ai_run_id', 'product_assets', ['ai_run_id'], unique=False)
    op.create_index('ix_product_assets_marketplace_id', 'product_assets', ['marketplace_id'], unique=False)
    op.create_index('ix_product_assets_org_status', 'product_assets', ['organization_id', 'status'], unique=False)
    op.create_index('ix_product_assets_product_position', 'product_assets', ['product_id', 'position'], unique=False)
    op.create_index('uq_product_assets_primary_per_product', 'product_assets', ['product_id'], unique=True, postgresql_where=sa.text('is_primary = true AND marketplace_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_product_assets_primary_per_product', table_name='product_assets', postgresql_where=sa.text('is_primary = true AND marketplace_id IS NULL'))
    op.drop_index('ix_product_assets_product_position', table_name='product_assets')
    op.drop_index('ix_product_assets_org_status', table_name='product_assets')
    op.drop_index('ix_product_assets_marketplace_id', table_name='product_assets')
    op.drop_index('ix_product_assets_ai_run_id', table_name='product_assets')
    op.drop_table('product_assets')
    op.drop_index('uq_listings_live_product_per_connection', table_name='listings', postgresql_where=sa.text("status <> 'ended'"))
    op.drop_index('uq_listings_external_id_per_connection', table_name='listings', postgresql_where=sa.text('external_listing_id IS NOT NULL'))
    op.drop_index('ix_listings_product_id', table_name='listings')
    op.drop_index('ix_listings_org_status', table_name='listings')
    op.drop_index('ix_listings_connection_status', table_name='listings')
    op.drop_table('listings')
    op.drop_index('ix_usage_tracking_org_period_start', table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.drop_index('uq_subscriptions_live_per_org', table_name='subscriptions', postgresql_where=sa.text("status IN ('trialing', 'active')"))
    op.drop_index('ix_subscriptions_organization_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_products_org_status_live', table_name='products', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('products')
    op.drop_index('ix_organization_members_user_id', table_name='organization_members')
    op.drop_index('ix_organization_members_org_status', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index('ix_marketplace_connections_org_status', table_name='marketplace_connections')
    op.drop_table('marketplace_connections')
    op.drop_index('ix_ai_runs_related_entity', table_name='ai_runs')
    op.drop_index('ix_ai_runs_org_status', table_name='ai_runs')
    op.drop_index('ix_ai_runs_org_created', table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index('ix_organizations_status_live', table_name='organizations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('organizations')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('plans')
    op.drop_table('marketplaces')
    # ### end Alembic commands ###
